fix: remove blue banner on specific pages
scroll-tech/frontends pull request #330
Opened 2023-04-27 06:49 UTC by Holybasil

2023-04-27 12:56 UTC, OrestTa requested changes

2023-04-27 12:56 UTC, OrestTa commented on src/components/Header/announcement.tsx
> +  if (pathname.includes("/alpha")) {
can we be more specific? this excludes e.g. https://deploy-preview-330--scroll-io.netlify.app/blog/alphaTestnet

2023-04-27 12:56 UTC, OrestTa commented on src/components/Header/announcement.tsx
> +    background: ${theme.palette.link.main};
good proactive thinking, thanks! :)

2023-04-28 02:33 UTC, Holybasil commented
It 

> btw @Holybasil note that we will probably be moving towards a single master navbar and a more flat URL structure to showcase the network features more (e.g. https://scroll.io/alpha/bridge -> https://scroll.io/bridge ) soon; cc @szgbo

what is the ETA? Also, are there detailed routing mapping rules between old path and new path?

2023-04-28 11:16 UTC, OrestTa commented
> It
> 
> > btw @Holybasil note that we will probably be moving towards a single master navbar and a more flat URL structure to showcase the network features more (e.g. https://scroll.io/alpha/bridge -> https://scroll.io/bridge ) soon; cc @szgbo
> 
> what is the ETA? Also, are there detailed routing mapping rules between old path and new path?

May 4, cf. https://scrollco.slack.com/archives/C03S72JTBGC/p1682631287030189 (incl. figma -> probably only one-level/flat URLs) & https://app.asana.com/0/0/1204307679338092/f

2023-04-28 11:16 UTC, OrestTa approved these changes

2023-04-28 11:16 UTC, merged