Dynamic wallet
scroll-tech/frontends pull request #801
Opened 2023-11-19 14:04 UTC by zzq0826

2023-11-20 02:33 UTC, Holybasil requested changes

2023-11-20 02:33 UTC, Holybasil commented on src/contexts/RainbowProvider/configs.tsx
> +  coinbaseWallet({ appName: "Scroll", chains }),
can we place the active wallet at the forefront? and do we still need to permanently display the Coinbase wallet?

2023-11-27 13:02 UTC, zzq0826 commented on src/contexts/RainbowProvider/configs.tsx
> +  coinbaseWallet({ appName: "Scroll", chains }),
Make sense. updated.

2023-11-28 01:03 UTC, Holybasil approved these changes, later dismissed

2023-11-28 09:33 UTC, merged