Add USD $amount to tokens
scroll-tech/frontends pull request #823
Opened 2023-12-04 02:07 UTC by zzq0826

2023-12-04 04:07 UTC, Holybasil commented
the layout is not suitable for mobile.
![CleanShot 2023-12-04 at 12 05 10@2x](https://github.com/scroll-tech/frontends/assets/21138718/e3f7827c-818c-456b-9f79-d3367fdbb27d)

2023-12-04 04:14 UTC, Holybasil requested changes

2023-12-04 04:14 UTC, Holybasil commented on src/hooks/useTokenPrice.ts
> +      const [ethPriceResponse, erc20PriceResponse] = await Promise.all([fetchEthPrice, fetchErc20Price])
can we use `Promise.allSettled` to avoid a situation where one failure causes all to fail?

2023-12-04 09:44 UTC, zzq0826 commented
> the layout is not suitable for mobile. ![CleanShot 2023-12-04 at 12 05 10@2x](https://private-user-images.githubusercontent.com/21138718/287587627-e3f7827c-818c-456b-9f79-d3367fdbb27d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODMzMDMsIm5iZiI6MTcwMTY4MzAwMywicGF0aCI6Ii8yMTEzODcxOC8yODc1ODc2MjctZTNmNzgyN2MtODE4Yy00NTZiLTlmNzktZDMzNjdmZGJiMjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDA5NDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZmVmZjcxZjdjODEwYWE5NTMxZmJkYzM0NzQxYWRmNjRjYzc5M2Y3ZjBmZmMwZmU3ZmY1NjM5NmM4OTAwYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CjgBTv6Zr63zJvngxpgwMaj_rrAmUauxFiFvEpq6h2k)

## Updated
<img width="380" alt="image" src="https://github.com/scroll-tech/frontends/assets/12936800/20546ff3-2d83-4ea0-b725-96d7f57c5d53">

2023-12-05 01:18 UTC, Holybasil submitted a review, later dismissed

2023-12-06 07:39 UTC, merged